package com.motionchallenge.attempt.application;

import java.time.LocalDateTime;

public record AttemptSummaryResponse(
        Long id,
        Long challengeId,
        String challengeTitle,
        Long memberId,
        String memberDisplayName,
        String memberEmail,
        int score,
        String status,
        String resultSource,
        boolean scoreAvailable,
        String resultHeadline,
        String resultSummary,
        String processingMode,
        boolean processingComplete,
        String processingNotice,
        String pendingTrackingId,
        String durableProgressStatus,
        String completionStrategy,
        Long elapsedSeconds,
        boolean autoRetryEnabled,
        int remainingAutoRetryCount,
        boolean autoRetryExhausted,
        String originalFileName,
        Integer poseSimilarity,
        Integer timingSimilarity,
        Integer stabilitySimilarity,
        String strongestArea,
        String weakestArea,
        String coachingTeaser,
        String retryFocus,
        String keepStableFocus,
        Long previousAttemptId,
        Integer previousAttemptScore,
        LocalDateTime previousAttemptedAt,
        Integer scoreDeltaFromPrevious,
        Integer poseDeltaFromPrevious,
        Integer timingDeltaFromPrevious,
        Integer stabilityDeltaFromPrevious,
        LocalDateTime attemptedAt) {
}
