package com.motionchallenge.attempt.application;

import java.time.LocalDateTime;
import java.util.List;

public record AttemptResultResponse(
        Long attemptId,
        Long challengeId,
        String challengeTitle,
        String attemptVideoUrl,
        int score,
        String status,
        String resultSource,
        boolean scoreAvailable,
        String resultHeadline,
        String resultSummary,
        AttemptFinalFeedbackResponse finalFeedback,
        List<AttemptJudgementCueResponse> judgementTimeline,
        String analyzerName,
        String processingMode,
        boolean processingComplete,
        String processingNotice,
        String pendingTrackingId,
        String videoOriginalFileName,
        String videoContentType,
        long videoSize,
        Integer poseSimilarity,
        Integer timingSimilarity,
        Integer stabilitySimilarity,
        String strongestArea,
        String weakestArea,
        String coachingTeaser,
        Long previousAttemptId,
        Integer previousAttemptScore,
        LocalDateTime previousAttemptedAt,
        Integer scoreDeltaFromPrevious,
        Integer poseDeltaFromPrevious,
        Integer timingDeltaFromPrevious,
        Integer stabilityDeltaFromPrevious,
        LocalDateTime attemptedAt) {

    public AttemptResultResponse withProcessingState(
            String nextProcessingMode,
            boolean nextProcessingComplete,
            String nextProcessingNotice) {
        return new AttemptResultResponse(
                attemptId,
                challengeId,
                challengeTitle,
                attemptVideoUrl,
                score,
                status,
                resultSource,
                scoreAvailable,
                resultHeadline,
                resultSummary,
                finalFeedback,
                judgementTimeline,
                analyzerName,
                nextProcessingMode,
                nextProcessingComplete,
                nextProcessingNotice,
                pendingTrackingId,
                videoOriginalFileName,
                videoContentType,
                videoSize,
                poseSimilarity,
                timingSimilarity,
                stabilitySimilarity,
                strongestArea,
                weakestArea,
                coachingTeaser,
                previousAttemptId,
                previousAttemptScore,
                previousAttemptedAt,
                scoreDeltaFromPrevious,
                poseDeltaFromPrevious,
                timingDeltaFromPrevious,
                stabilityDeltaFromPrevious,
                attemptedAt);
    }
}
