spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:motion_challenge}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${MYSQL_TIMEZONE:Asia/Seoul}
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: ${MYSQL_TIMEZONE:Asia/Seoul}
        boot:
          allow_jdbc_metadata_access: false
